### PR TITLE
feat: set active color of all levels to red and set hover color of all levels to black

### PR DESCRIPTION
**Pull request by jonasmueller1**
black for active color of sub-levels is not very obvious
level 1 didn't have any different hover color

sorry, I can't test it on a live system... thank you.

### CODE REVIEW

**Comment by markocupic** [comment]
@jonasmueller1: Thank you!

**Comment by markocupic** [comment]
Hm... could you check this? I think the behaviour for active links is the same as before.

**Comment by jonasmueller1** [comment]
Yes, unfortunately, the behaviour is still the same.
Sorry, I could not test it, because I don't have the system installation. I just did brain work ;-)

I still see this in the html output:
```
#header .navbar-header .mod_navigation ul.level_3 > li.active > strong, #header .navbar-header .mod_navigation ul.level_3 > li > a > span:hover, #header .navbar-header .mod_navigation ul.level_3 > li > a > strong:hover {
  color: #000000 !important;
}
```

I replaced the #000000 with red and black:
```
- $color-level-2-active: #000000;
+ $color-level-2-active: $red;
+ $color-level-2-hover: $dark;
```

Are you sure that you deployed it to the proper system instance (and not test system)? ;-)
Suggestion: You can reopen this issue and we will have a look later whenever it suits best for you...

**Comment by markocupic** [comment]
image

**Comment by markocupic** [comment]
Hm.... everything should be up to date.

**Comment by markocupic** [comment]
One Moment, I think it is a cache issue.

**Comment by markocupic** [comment]
Ok, I found it. I hat to touch the `vendor/markocupic/contao-theme-sac-pilatus/src/Resources/contao/files/theme-sac-pilatus/scss/main.scss` as well. In production mode the sass transpiler regenerates the stylesheet only, if there are changes in `main.scss`.

**Comment by markocupic** [comment]
image
It works.But I don't like the red color on the blue background. What do you think?

**Comment by markocupic** [comment]
https://user-images.githubusercontent.com/1525166/169667716-88a6ba26-877b-47ba-8cff-d5e3c1726a6b.mp4

Nor there should be any color change when the user hovers a not clickable level_2 "link" in the megamenu.

**Comment by jonasmueller1** [comment]
Okay, I improved it again in pull request 6:
https://github.com/markocupic/contao-theme-sac-pilatus/pull/6

Sorry for that and thank you.

**Pull request merged**
